# Data Load

In [1]:
import pandas as pd

In [2]:
from modules.data_store import data_store

There is data stored
Last data fetch completed

In [3]:
data_store = data_store()

Load the saved pickle file

In [4]:
trial = data_store.return_last_trial()
df = data_store.return_dict_df()[trial]
df.head()

,DAT,predicted_weight_g,train/test,file_num,obs_time,내부온도관측치,내부습도관측치,co2관측치,ec관측치,시간당분무량,...,시간당적색광량,일간누적적색광량,시간당청색광량,일간누적청색광량,시간당총광량,일간누적총광량,sum,total_sum,weight,target
0,1,1.918119,CASE,08,00:00,27.680000,73.026667,466.750000,0.0,61.7,...,0.0,0.0,0.0,0.0,0.0,0.0,629.156667,381790.957381,0.001648,0.003161
1,1,1.918119,CASE,08,01:00,27.770000,73.120000,464.516667,0.0,61.7,...,0.0,0.0,0.0,0.0,0.0,0.0,627.106666,381790.957381,0.001643,0.003151
2,1,1.918119,CASE,08,02:00,27.766666,73.130001,466.233333,0.0,61.7,...,0.0,0.0,0.0,0.0,0.0,0.0,628.830000,381790.957381,0.001647,0.003159
3,1,1.918119,CASE,08,03:00,27.896666,73.488334,468.466667,0.0,61.7,...,0.0,0.0,0.0,0.0,0.0,0.0,631.551667,381790.957381,0.001654,0.003173
4,1,1.918119,CASE,08,04:00,27.921666,73.543333,471.550000,0.0,61.7,...,0.0,0.0,0.0,0.0,0.0,0.0,634.715000,381790.957381,0.001662,0.003189

# Target값 조정

In [6]:
sum_cols = [ '내부온도관측치',
 '내부습도관측치',
 'co2관측치',
 'ec관측치',
 '시간당분무량',
 '시간당백색광량',
 '시간당적색광량',
 '시간당청색광량',
 '시간당총광량']

In [7]:
df['sum'] = df[sum_cols].sum(axis=1)
df.head(1)

,DAT,predicted_weight_g,train/test,file_num,obs_time,내부온도관측치,내부습도관측치,co2관측치,ec관측치,시간당분무량,일간누적분무량,시간당백색광량,일간누적백색광량,시간당적색광량,일간누적적색광량,시간당청색광량,일간누적청색광량,시간당총광량,일간누적총광량,sum
0,1,1.918119,CASE,08,00:00,27.68,73.026667,466.75,0.0,61.7,61.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,629.156667

In [22]:
df[(df['DAT']==1)&(df['train/test']=='CASE')&(df['file_num']=='01')]['sum'].sum()

558111.7754508969

In [27]:
total_sum_df = df[['DAT','train/test','file_num','sum']].groupby(['DAT','train/test','file_num']).sum().reset_index()
total_sum_df.columns = ['DAT','train/test','file_num','total_sum']

base_df = pd.merge(df,total_sum_df,how='inner',on=['DAT','train/test','file_num'])
base_df['weight'] = base_df['sum'] / base_df['total_sum']
base_df['target'] = base_df['predicted_weight_g'] * base_df['weight']
base_df

,DAT,predicted_weight_g,train/test,file_num,obs_time,내부온도관측치,내부습도관측치,co2관측치,ec관측치,시간당분무량,...,시간당적색광량,일간누적적색광량,시간당청색광량,일간누적청색광량,시간당총광량,일간누적총광량,sum,total_sum,weight,target
0,1,1.918119,CASE,08,00:00,27.680000,73.026667,466.750000,0.000000,61.7,...,0.0,0.0,0.0,0.0,0.0000,0.000,629.156667,381790.957381,0.001648,0.003161
1,1,1.918119,CASE,08,01:00,27.770000,73.120000,464.516667,0.000000,61.7,...,0.0,0.0,0.0,0.0,0.0000,0.000,627.106666,381790.957381,0.001643,0.003151
2,1,1.918119,CASE,08,02:00,27.766666,73.130001,466.233333,0.000000,61.7,...,0.0,0.0,0.0,0.0,0.0000,0.000,628.830000,381790.957381,0.001647,0.003159
3,1,1.918119,CASE,08,03:00,27.896666,73.488334,468.466667,0.000000,61.7,...,0.0,0.0,0.0,0.0,0.0000,0.000,631.551667,381790.957381,0.001654,0.003173
4,1,1.918119,CASE,08,04:00,27.921666,73.543333,471.550000,0.000000,61.7,...,0.0,0.0,0.0,0.0,0.0000,0.000,634.715000,381790.957381,0.001662,0.003189
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22171,28,0.000000,TEST,02,19:00,26.960000,56.620000,542.616667,1.067239,769.0,...,0.0,0.0,0.0,0.0,12.3764,209656.216,1421.016706,446639.947445,0.003182,0.000000
22172,28,0.000000,TEST,02,20:00,26.211667,57.241667,540.583333,1.074064,0.0,...,0.0,0.0,0.0,0.0,0.0000,209656.216,625.110731,446639.947445,0.001400,0.000000
22173,28,0.000000,TEST,02,21:00,25.368333,56.310000,530.800000,1.078533,769.0,...,0.0,0.0,0.0,0.0,0.0000,209656.216,1382.556867,446639.947445,0.003095,0.000000
22174,28,0.000000,TEST,02,22:00,25.256667,57.343333,540.466667,1.078533,0.0,...,0.0,0.0,0.0,0.0,0.0000,209656.216,624.145200,446639.947445,0.001397,0.000000
22175,28,0.000000,TEST,02,23:00,24.575000,56.585000,536.166667,1.082081,769.0,...,0.0,0.0,0.0,0.0,0.0000,209656.216,1387.408748,446639.947445,0.003106,0.000000

In [32]:
def load_data(df,DAT,train_test,file_num):
    return df[(df['DAT']==DAT)&(df['train/test']==train_test)&(df['file_num']==file_num)]
load_data(base_df,28,'CASE','02')

,DAT,predicted_weight_g,train/test,file_num,obs_time,내부온도관측치,내부습도관측치,co2관측치,ec관측치,시간당분무량,...,시간당적색광량,일간누적적색광량,시간당청색광량,일간누적청색광량,시간당총광량,일간누적총광량,sum,total_sum,weight,target
12072,28,65.505384,CASE,02,00:00:00.,25.600000,78.000000,660.000000,0.0,61.7,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,825.300000,246823.01124,0.003344,0.219030
12073,28,65.505384,CASE,02,01:00:00.,23.348333,78.896668,623.516667,0.0,61.7,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,787.461668,246823.01124,0.003190,0.208988
12074,28,65.505384,CASE,02,01:59:59.,23.138334,78.956667,624.100000,0.0,61.7,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,787.895001,246823.01124,0.003192,0.209103
12075,28,65.505384,CASE,02,02:59:59.,23.051667,78.820000,623.966667,0.0,61.7,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,787.538334,246823.01124,0.003191,0.209008
12076,28,65.505384,CASE,02,03:59:59.,22.896666,78.930001,624.633333,0.0,61.7,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,788.160001,246823.01124,0.003193,0.209173
12077,28,65.505384,CASE,02,04:59:59.,22.951666,79.093333,626.600000,0.0,61.7,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,790.345000,246823.01124,0.003202,0.209753
12078,28,65.505384,CASE,02,05:59:59.,23.748333,79.806667,605.366667,0.0,123.4,...,1087.2036,1087.2036,1029.1905,1029.1905,2116.3941,2116.3941,5065.109867,246823.01124,0.020521,1.344251
12079,28,65.505384,CASE,02,06:59:59.,25.805000,76.858335,545.550000,0.0,123.4,...,3536.3076,4623.5112,3347.6105,4376.8010,6883.9181,9000.3122,14539.449535,246823.01124,0.058906,3.858685
12080,28,65.505384,CASE,02,07:59:59.,27.921667,76.693333,515.933333,0.0,123.4,...,4878.3504,9501.8616,4618.0420,8994.8430,9496.3924,18496.7046,19736.733133,246823.01124,0.079963,5.238014
12081,28,65.505384,CASE,02,08:59:59.,27.823333,76.783334,539.300000,0.0,123.4,...,4881.6600,14383.5216,4621.1750,13616.0180,9502.8350,27999.5396,19772.976667,246823.01124,0.080110,5.247632
12082,28,65.505384,CASE,02,09:59:59.,27.518333,76.611667,558.983333,0.0,123.4,...,4881.6600,19265.1816,4621.1750,18237.1930,9502.8350,37502.3746,19792.183333,246823.01124,0.080188,5.252730
12083,28,65.505384,CASE,02,10:59:59.,26.931666,76.645001,571.766667,0.0,123.4,...,4881.6600,24146.8416,4621.1750,22858.3680,9502.8350,47005.2096,19804.413334,246823.01124,0.080237,5.255975
12084,28,65.505384,CASE,02,11:59:59.,27.193333,76.615001,592.950000,0.0,123.4,...,4881.6600,29028.5016,4621.1750,27479.5430,9502.8350,56508.0446,19825.828334,246823.01124,0.080324,5.261659
12085,28,65.505384,CASE,02,12:59:59.,27.596667,76.176667,582.666667,0.0,123.4,...,4881.6600,33910.1616,4621.1750,32100.7180,9502.8350,66010.8796,19815.510001,246823.01124,0.080282,5.258920
12086,28,65.505384,CASE,02,13:59:59.,27.605000,75.306667,642.766667,0.0,123.4,...,4881.6600,38791.8216,4621.1750,36721.8930,9502.8350,75513.7146,19874.748334,246823.01124,0.080522,5.274642
12087,28,65.505384,CASE,02,14:59:59.,27.480000,73.858333,709.466667,0.0,123.4,...,4881.6600,43673.4816,4621.1750,41343.0680,9502.8350,85016.5496,19939.875000,246823.01124,0.080786,5.291926
12088,28,65.505384,CASE,02,15:59:59.,27.576667,73.411666,660.833333,0.0,123.4,...,4881.6600,48555.1416,4621.1750,45964.2430,9502.8350,94519.3846,19890.891667,246823.01124,0.080588,5.278926
12089,28,65.505384,CASE,02,16:59:59.,27.250000,72.680000,654.816667,0.0,123.4,...,4881.6600,53436.8016,4621.1750,50585.4180,9502.8350,104022.2196,19883.816666,246823.01124,0.080559,5.277049
12090,28,65.505384,CASE,02,17:59:59.,26.553333,72.165000,603.916667,0.0,61.7,...,3698.4780,57135.2796,3501.1275,54086.5455,7199.6055,111221.8251,15163.546000,246823.01124,0.061435,4.024316
12091,28,65.505384,CASE,02,18:59:59.,25.880000,74.249168,611.450000,0.0,61.7,...,1244.4096,58379.6892,1178.0080,55264.5535,2422.4176,113644.2427,5618.114368,246823.01124,0.022762,1.491015
12092,28,65.505384,CASE,02,19:59:59.,25.928333,76.351667,651.483333,0.0,61.7,...,0.0000,58379.6892,0.0000,55264.5535,0.0000,113644.2427,815.463333,246823.01124,0.003304,0.216419
12093,28,65.505384,CASE,02,20:59:59.,25.981667,76.766667,682.100000,0.0,61.7,...,0.0000,58379.6892,0.0000,55264.5535,0.0000,113644.2427,846.548334,246823.01124,0.003430,0.224669
12094,28,65.505384,CASE,02,21:59:59.,25.758333,77.206665,675.300000,0.0,61.7,...,0.0000,58379.6892,0.0000,55264.5535,0.0000,113644.2427,839.964998,246823.01124,0.003403,0.222922
12095,28,65.505384,CASE,02,22:59:59.,25.705000,77.416667,666.316667,0.0,61.7,...,0.0000,58379.6892,0.0000,55264.5535,0.0000,113644.2427,831.138333,246823.01124,0.003367,0.220579

- data save

In [59]:
data_store.add_df(all_df = base_df)
data_store.save_pkl()

# Start EBM

In [5]:
from modules import config
config.input_cols

['DAT',
 'obs_time',
 '내부온도관측치',
 '내부습도관측치',
 'co2관측치',
 'ec관측치',
 '시간당분무량',
 '일간누적분무량',
 '시간당백색광량',
 '일간누적백색광량',
 '시간당적색광량',
 '일간누적적색광량',
 '시간당청색광량',
 '일간누적청색광량',
 '시간당총광량',
 '일간누적총광량']

In [9]:
set(base_df['train/test'])

{'CASE', 'TEST'}

In [10]:
train_df = base_df[base_df['train/test']=='CASE']
test_df = base_df[base_df['train/test']=='TEST']

In [11]:
from interpret.glassbox import ExplainableBoostingRegressor

X_train = train_df[config.input_cols]
y_train = train_df['target']

ebm = ExplainableBoostingRegressor()
ebm.fit(X_train, y_train)

ExplainableBoostingRegressor(feature_names=['DAT', 'obs_time', '내부온도관측치',
                                            '내부습도관측치', 'co2관측치', 'ec관측치',
                                            '시간당분무량', '일간누적분무량', '시간당백색광량',
                                            '일간누적백색광량', '시간당적색광량', '일간누적적색광량',
                                            '시간당청색광량', '일간누적청색광량', '시간당총광량',
                                            '일간누적총광량', 'DAT x 시간당총광량',
                                            'DAT x 시간당백색광량', 'DAT x 일간누적총광량',
                                            'DAT x obs_time', 'DAT x 시간당분무량',
                                            'DAT x 내부온도관측치', 'DAT x 일간누적분무량',
                                            '내부습도관측치 x 시간당총광량', 'DAT x co2관측치',
                                            'DAT x 일간누적백색광량'],
                             feature_...'continuous', 'categorical',
                                            'continuous', 'continuous',
                                            'continuous', 'continuous',
                                            'continuous', 'continuous',
                                            'continuous', 'continuous',
                                            'continuous', 'continuous',
                                            'continuous', 'continuous',
                                            'continuous', 'continuous',
                                            'interaction', 'interaction',
                                            'interaction', 'interaction',
                                            'interaction', 'interaction',
                                            'interaction', 'interaction',
                                            'interaction', 'interaction'])

In [40]:
from interpret import show
from interpret.data import Marginal

marginal = Marginal().explain_data(X_train, y_train, name = 'Train Data')
show(marginal)

/Users/youngyong/opt/anaconda3/lib/python3.7/site-packages/interpret/visual/udash.py:5: UserWarning:
The dash_html_components package is deprecated. Please replace
`import dash_html_components as html` with `from dash import html`
  import dash_html_components as html
/Users/youngyong/opt/anaconda3/lib/python3.7/site-packages/interpret/visual/udash.py:6: UserWarning:
The dash_core_components package is deprecated. Please replace
`import dash_core_components as dcc` with `from dash import dcc`
  import dash_core_components as dcc
/Users/youngyong/opt/anaconda3/lib/python3.7/site-packages/interpret/visual/udash.py:7: UserWarning:
The dash_table package is deprecated. Please replace
`import dash_table` with `from dash import dash_table`

Also, if you're using any of the table format helpers (e.g. Group), replace
`from dash_table.Format import Group` with
`from dash.dash_table.Format import Group`
  import dash_table as dt

In [41]:
ebm_global = ebm.explain_global()
show(ebm_global)

In [62]:
cols = config.input_cols

def get_eachCols_EBM_score(ebm_global, cols):
    EBM_cols_dict = dict()
    for i in range(len(cols)):
        EBM_cols_dict[cols[i]] = {'values':ebm_global.data(i)['names'],'scores':list(ebm_global.data(i)['scores'])}
    return EBM_cols_dict
EBM_cols_dict = get_eachCols_EBM_score(ebm_global, cols)
# EBM_cols_dict['DAT']

In [47]:
import numpy as np
def get_EBM_MinMax_scorePoint(df, EBM_cols_dict):
    EBM_Score_Min_max_df = dict()
    for k,v in EBM_cols_dict.items():
        EBM_Score_Min_max_df[k] = {'Unique':len(set(df[k])),'Max_Point':v['values'][v['scores'].index(max(v['scores']))],'Min_Point':v['values'][v['scores'].index(min(v['scores']))] ,'Max_Score' : int(max(v['scores'])), 'Min_Score' : int(min(v['scores'])), 'Midean' : int(np.median(v['scores']))}
    EBM_Score_Min_max_df = pd.DataFrame(EBM_Score_Min_max_df).transpose()
    EBM_Score_Min_max_df['Range_Score'] = EBM_Score_Min_max_df['Max_Score'] - EBM_Score_Min_max_df['Min_Score']
    return EBM_Score_Min_max_df.sort_values('Range_Score',ascending=False)
get_EBM_MinMax_scorePoint(train_df,EBM_cols_dict)

         Unique Max_Point  Min_Point Max_Score Min_Score Midean Range_Score
DAT          28      27.5        3.5         2         0      0           2
co2관측치    14246      60.4    552.408         2         0      0           2
시간당총광량     2511   9242.35    36515.6         0        -2      0           2
obs_time     70     06:00  01:59:59.         0        -1      0           1
ec관측치     16306   3.65794    0.24145         0        -1      0           1
시간당분무량     1869   2259.73      123.4         1         0      0           1
시간당백색광량    1144   4641.15    8559.83         0        -1      0           1
시간당적색광량     888   1948.53     8687.7         1         0      0           1
일간누적적색광량   2595   154.724    20425.2         0        -1      0           1
시간당청색광량     960   9164.02    4621.17         1         0      0           1
일간누적청색광량   2494    151246     100804         1         0      0           1
내부온도관측치   17416      25.9    17.6925         0         0      0           0
내부습도관측치   17964   76.5727    84.6392         0         0      0           0
일간누적분무량    6013   25879.4    3792.26         0         0      0           0
일간누적백색광량   4021    254638     206599         0         0      0           0
일간누적총광량    7761    121527     557972         0         0      0           0

해석해보자면 DAT은 클수록, co2관측치는 낮을수록 target값에 영향을 높게 준다.  
  
하지만 시간당 총광량은 9200수준이 36000수준보다 target에 영향을 높게 주는것으로 보인다.  이상하다.. 이부분을 EDA해 나가봐야겠다.  

> EDA 순서
> - 시간당 총광량
> - obs_time 확인 후 시간:00 으로 모두 고치기

In [55]:
base_df['시간당총광량'].describe()

count     22176.000000
mean       9272.340787
std        9608.289535
min     -165735.710800
25%           0.000000
50%        9242.350000
75%       18255.190000
max       37892.400000
Name: 시간당총광량, dtype: float64

- 시간당 총광량에 마이너스 값 존재 확인

# Base test predict

In [12]:
X_test = test_df[config.input_cols]
y_test = test_df['target']


test_df['predicted_weight_g'] = ebm.predict(X_test)

/Users/youngyong/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

In [13]:
test_df.head()

,DAT,predicted_weight_g,train/test,file_num,obs_time,내부온도관측치,내부습도관측치,co2관측치,ec관측치,시간당분무량,...,시간당적색광량,일간누적적색광량,시간당청색광량,일간누적청색광량,시간당총광량,일간누적총광량,sum,total_sum,weight,target
18816,1,0.059478,TEST,05,00:00:00.,25.675,51.99,508.5,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,586.165,332711.959331,0.001762,0.0
18817,1,0.096088,TEST,05,01:00:00.,25.675,51.99,508.5,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,586.165,332711.959331,0.001762,0.0
18818,1,0.109053,TEST,05,02:00:00.,25.675,51.99,508.5,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,586.165,332711.959331,0.001762,0.0
18819,1,0.154528,TEST,05,03:00:00.,25.675,51.99,508.5,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,586.165,332711.959331,0.001762,0.0
18820,1,0.207238,TEST,05,04:00:00.,25.675,51.99,508.5,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,586.165,332711.959331,0.001762,0.0

In [14]:
base_rslt_df = test_df[['DAT','file_num','predicted_weight_g']].groupby(['DAT','file_num']).sum().reset_index()
def predict_rslt_weight(x):
    if x < 0 :
        return 0
    else : 
        return x

base_rslt_df['predicted_weight_g'] = base_rslt_df['predicted_weight_g'].apply(predict_rslt_weight)
# base_rslt_df = base_rslt_df.set_index('DAT')
base_rslt_df

     DAT file_num  predicted_weight_g
0      1       01            6.263632
1      1       02            0.154602
2      1       03            0.000000
3      1       04            0.803110
4      1       05            0.018673
..   ...      ...                 ...
135   28       01          130.433610
136   28       02           79.700797
137   28       03           21.158445
138   28       04          136.753058
139   28       05           91.661121

[140 rows x 3 columns]

In [15]:
df.columns

Index(['DAT', 'predicted_weight_g', 'train/test', 'file_num', 'obs_time',
       '내부온도관측치', '내부습도관측치', 'co2관측치', 'ec관측치', '시간당분무량', '일간누적분무량', '시간당백색광량',
       '일간누적백색광량', '시간당적색광량', '일간누적적색광량', '시간당청색광량', '일간누적청색광량', '시간당총광량',
       '일간누적총광량', 'sum', 'total_sum', 'weight', 'target'],
      dtype='object')

In [23]:
file_num_list = set(base_rslt_df['file_num'])
test_target_list = [] 
file_path = './open/sample_submission/'
for file_num in file_num_list:
    test_target_file = file_path+'TEST_'+file_num+'.csv'
    print(test_target_file)
    test_target_list.append(test_target_file)
    base_rslt_df[base_rslt_df['file_num']==file_num][['DAT','predicted_weight_g']].to_csv(test_target_file,index=False)

./open/sample_submission/TEST_03.csv
./open/sample_submission/TEST_05.csv
./open/sample_submission/TEST_04.csv
./open/sample_submission/TEST_02.csv
./open/sample_submission/TEST_01.csv

In [36]:
# import zipfile
# import os
# os.chdir(file_path)
# submission = zipfile.ZipFile("./submission.zip", 'w')
# for path in test_target_list:
#     print(path)
#     path = path.split('/')[-1]
#     submission.write(path)
# submission.close()
# os.chdir('~')