### 데이콘에서 제공한 변수별 제한 수치
- 시간당 내부 평균온도: 4도~40도  
- 시간당 내부 평균습도: 0% ~ 100%  
- 시간당 내부 평균 co2 농도 : 0ppm ~ 1200 ppm  
- 시간당 평균 EC : 0 ~ 8  
- 시간당 분무량 : 0 ~ 3000 / 일간 누적 분무량 0 ~ 72,000  
- 시간당 백색광량 : 0 ~ 120,000 / 일간 누적 백색광량 0 ~ 2,880,000  
- 시간당 적색광량 : 0 ~ 120,000 / 일간 누적 적색광량 0 ~ 2,880,000   
- 시간당 청색광량 : 0 ~ 120,000 / 일간 누적 청색광량 0 ~ 2,880,000  
- 시간당 총광량 : 0 ~ 120,000 / 일간 누적 총광량 0 ~ 2,880,000

In [ ]:
diff_cols  = ['diff_온도','diff_습도','diff_co2','diff_ec']
df['diff_온도']=df.groupby(['DAT','train/test','file_num']).shift(1)

# Data Load

In [1]:
import pandas as pd

In [2]:
from modules.data_store import data_store

There is data stored
Last data fetch completed

In [3]:
data_store = data_store()

Load the saved pickle file

In [7]:
trial = data_store.return_last_trial()
df = data_store.dict_df[trial]
df

,DAT,predicted_weight_g,train/test,file_num,obs_time,내부온도관측치,내부습도관측치,co2관측치,ec관측치,시간당분무량,...,시간당적색광량,일간누적적색광량,시간당청색광량,일간누적청색광량,시간당총광량,일간누적총광량,sum,total_sum,weight,target
0,1,1.918119,CASE,08,00:00,27.680000,73.026667,466.750000,0.000000,61.7,...,0.0,0.0,0.0,0.0,0.0000,0.000,629.156667,381790.957381,0.001648,0.003161
1,1,1.918119,CASE,08,01:00,27.770000,73.120000,464.516667,0.000000,61.7,...,0.0,0.0,0.0,0.0,0.0000,0.000,627.106666,381790.957381,0.001643,0.003151
2,1,1.918119,CASE,08,02:00,27.766666,73.130001,466.233333,0.000000,61.7,...,0.0,0.0,0.0,0.0,0.0000,0.000,628.830000,381790.957381,0.001647,0.003159
3,1,1.918119,CASE,08,03:00,27.896666,73.488334,468.466667,0.000000,61.7,...,0.0,0.0,0.0,0.0,0.0000,0.000,631.551667,381790.957381,0.001654,0.003173
4,1,1.918119,CASE,08,04:00,27.921666,73.543333,471.550000,0.000000,61.7,...,0.0,0.0,0.0,0.0,0.0000,0.000,634.715000,381790.957381,0.001662,0.003189
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22171,28,0.000000,TEST,02,19:00,26.960000,56.620000,542.616667,1.067239,769.0,...,0.0,0.0,0.0,0.0,12.3764,209656.216,1421.016706,446639.947445,0.003182,0.000000
22172,28,0.000000,TEST,02,20:00,26.211667,57.241667,540.583333,1.074064,0.0,...,0.0,0.0,0.0,0.0,0.0000,209656.216,625.110731,446639.947445,0.001400,0.000000
22173,28,0.000000,TEST,02,21:00,25.368333,56.310000,530.800000,1.078533,769.0,...,0.0,0.0,0.0,0.0,0.0000,209656.216,1382.556867,446639.947445,0.003095,0.000000
22174,28,0.000000,TEST,02,22:00,25.256667,57.343333,540.466667,1.078533,0.0,...,0.0,0.0,0.0,0.0,0.0000,209656.216,624.145200,446639.947445,0.001397,0.000000
22175,28,0.000000,TEST,02,23:00,24.575000,56.585000,536.166667,1.082081,769.0,...,0.0,0.0,0.0,0.0,0.0000,209656.216,1387.408748,446639.947445,0.003106,0.000000

In [ ]:
# diff_cols  = ['diff_온도','diff_습도','diff_co2','diff_ec']
# df['diff_온도']=df.groupby(['DAT','train/test','file_num']).shift(1)